{
  "text-color": "#2a2920",
  "background-color": "#faf9f5",
  "line-number-color": "#b5b2ab",
  "line-number-background-color": null,
  "text-styles": {
    "Normal": {
      "text-color": "#2a2920",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Comment": {
      "text-color": "#6c675f",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "Documentation": {
      "text-color": "#6c675f",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "Annotation": {
      "text-color": "#7c619a",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "CommentVar": {
      "text-color": "#6c675f",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "Keyword": {
      "text-color": "#876032",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "ControlFlow": {
      "text-color": "#876032",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "DataType": {
      "text-color": "#527594",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Function": {
      "text-color": "#9a4929",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "String": {
      "text-color": "#3f643c",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "VerbatimString": {
      "text-color": "#3f643c",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "SpecialString": {
      "text-color": "#3f643c",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Char": {
      "text-color": "#3f643c",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "SpecialChar": {
      "text-color": "#7c619a",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Constant": {
      "text-color": "#7c619a",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "DecVal": {
      "text-color": "#7c619a",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "BaseN": {
      "text-color": "#7c619a",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Float": {
      "text-color": "#7c619a",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Variable": {
      "text-color": "#2a2920",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Operator": {
      "text-color": "#3d3929",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "BuiltIn": {
      "text-color": "#9a4929",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Import": {
      "text-color": "#7c619a",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Preprocessor": {
      "text-color": "#7c619a",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Extension": {
      "text-color": "#9a4929",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Attribute": {
      "text-color": "#876032",
      "background-color": null,
      "bold": false,
      "italic": true,
      "underline": false
    },
    "Other": {
      "text-color": "#2a2920",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Information": {
      "text-color": "#3f643c",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Warning": {
      "text-color": "#6e5c20",
      "background-color": null,
      "bold": false,
      "italic": false,
      "underline": false
    },
    "Alert": {
      "text-color": "#6e5c20",
      "background-color": null,
      "bold": true,
      "italic": false,
      "underline": false
    },
    "Error": {
      "text-color": "#b05555",
      "background-color": null,
      "bold": true,
      "italic": false,
      "underline": false
    }
  }
}
